//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinglePageToDo.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoLogger
    {
        public int MessageId { get; set; }
        public string MessageText { get; set; }
        public System.DateTime DatePosted { get; set; }
    }
}
